mp:
  messaging:
    incoming:
      f1-live-processed:
        topic: test-f1-live-processed
        connector: smallrye-kafka
        "auto.offset.reset": earliest
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer

smallrye:
  messaging:
    observation:
      enabled: true

quarkus:
  #rest:
    #path: "f1/api/v1"
  log:
    level: INFO
  package:
    jar:
      aot:
        enabled: true
  datasource:
    db-kind: postgresql
      #username: <your username>
      #password: <your password>
    jdbc:
      #url: jdbc:postgresql://localhost:5432/hibernate_orm_test
      max-size: 50
      min-size: 10
      acquisition-timeout: 5s
  jib:
    base-jvm-image: gcr.io/distroless/java25-debian13

app:
  database: app
  session-info:
    table: live_session_info
  track-status:
    table: live_track_status
  race-control-message:
    table: live_race_control_messages
  weather-data:
    table: live_weather_data
  log:
    source: "Default config file."

"%prod":
  kafka:
    bootstrap:
      servers: kafka-main-kafka-bootstrap:9092

"%test":
  quarkus:
    devservices:
      enabled: true