apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: web-ui-svelte
build:
  local:
    push: false                                            # When building locally, do not push the image to a repository
  artifacts:
  - image: web-ui-svelte                                         # Image name
    context: .
    docker:
    #jib:                                                   # Use Jib as the container builder
    #  args:
    #    - Dquarkus.container-image.build=true
      #fromImage: "gcr.io/distroless/java21-debian12"       # Use a "distroless" base image
  tagPolicy:
    dateTime:                                              # The image will be tagged with the build timestamp
      format: "20060102T150405"
      timezone: "UTC"
manifests:
  kustomize:
    paths:
      - ./kubernetes-manifests/
