apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: default
commonLabels:
  app.kubernetes.io/name: signalr-mock-server

resources:
  - signalr-mock-server.deployment.yaml

# The generator will convert the config.yaml file into a K8 config map which can be mapped
# into the container
configMapGenerator:
  - name: signalr-mock-server-config
    files:
      - config.yaml=application.yaml

generatorOptions:
  disableNameSuffixHash: true