apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: f1-db
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18
  postgresql:
    parameters:
      shared_buffers: 128MB

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 2Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"
