apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - kafka-main.kafkanodepool.yaml
  - kafka-main-kraft.kafka.yaml
  - kafka-main-f1-live-raw.kafkatopic.yaml
  - f1-db.postgresql.yamln
