quarkus:
  log:
    level: INFO

%prod:
  kafka:
    bootstrap:
      servers: kafka-main-kafka-bootstrap.kafka.svc.cluster.local:9092

mp:
  messaging:
    incoming:
      words-in:
        auto-offset-reset: earliest
        topic: words
    outgoing:
      words-out:
        topic: words