# Custom configuration options should be added to this file. It will be mapped into the
# application pod and made available to the container as /config/config.yaml

# Default config settings for your module
source:
  baseUrl: "https://livetiming.formula1.com/signalr/"
#  baseUrl: "http://livetiming.kinnovatio.local/signalr/"

# Configuration for metrics.
metrics:
  enable: true