apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: signalr-to-kafka
build:
  local:
    push: false                                            # When building locally, do not push the image to a repository
  artifacts:
  - image: signalr-to-kafka                                         # Image name
    context: .
    jib:                                                   # Use Jib as the container builder
      fromImage: "eclipse-temurin:25-jre-jammy"       # Use a "distroless" base image
  tagPolicy:
    dateTime:                                              # The image will be tagged with the build timestamp
      format: "20060102T150405"
      timezone: "UTC"
manifests:
  kustomize:
    paths:
      - ./kubernetes-manifests/
