apiVersion: v1
kind: Service
metadata:
  name: f1-livetiming-test-bridge
spec:
  selector:
    app: f1-livetiming-test-bridge
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort