apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-livetiming-test-bridge
  labels:
    app: f1-livetiming-test-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f1-livetiming-test-bridge
  template:
    metadata:
      labels:
        app: f1-livetiming-test-bridge
    spec:
      containers:
        - name: f1-livetiming-test-bridge
          image: local/f1-livetiming-test-bridge
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75.0"

          volumeMounts:
            - mountPath: "/home/jboss/config"                  # The file path used by SmallRye to search for config files.
              name: config                          # Name of the "volume" to mount. Specified below in the volumes section.
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      # Map the config map generated by Kustomize as a file volume
      volumes:
        - name: config                              # Give the volume a name you can reference in the container spec.
          configMap:                                # Specifies that you source the data from a ConfigMap.
            name: f1-livetiming-test-bridge-config                    # The name of the ConfigMap to read from
#     serviceAccountName: extractor-default
