apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: signalr-mock-server
build:
  local:
    push: false                                            # When building locally, do not push the image to a repository
  artifacts:
  - image: signalr-mock-server                                         # Image name
    context: .
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
          - src/**
          - kubernetes-manifests/**
    #jib:                                                   # Use Jib as the container builder
    #  args:
    #    - Dquarkus.container-image.build=true
      #fromImage: "gcr.io/distroless/java21-debian12"       # Use a "distroless" base image
  tagPolicy:
    dateTime:                                              # The image will be tagged with the build timestamp
      format: "20060102T150405"
      timezone: "UTC"
manifests:
  kustomize:
    paths:
      - ./kubernetes-manifests/

profiles:
  - name: local
    activation:
      - kubeContext: docker-desktop
    requiresAllActivations: true
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: local/signalr-mock-server
  - name: win
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: local/signalr-mock-server
      - op: replace
        path: /build/artifacts/0/custom/buildCommand
        value: "./build.ps1"
