name: ci-signalr-mock-server
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "signalr-mock-server/**"
      
jobs:
  build-signalr-mock-server:
    uses: "signalr-mock-server/.github/workflows/java-maven-skaffold-build.yml"
    with:
      repositoryFolder: "./signalr-mock-server/" 