name: package-signalr-mock-server
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "signalr-mock-server/**"
      
jobs:
  package-signalr-mock-server:
    uses: "signalr-mock-server/.github/workflows/java-maven-skaffold-build-push-ghcr.yml@main"
    with:
      repositoryFolder: "./signalr-mock-server/"
    secrets: inherit